---
title: "LE DB Resources"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Background

This repository includes some of my examples on how to use OSS technologies with databases for network analysis. The goal here is to provide access to my slides, code, and notes.

If you have any questions or problems that you would need help with, please start an issue, [here](https://github.com/cjcallag/le-db/issues).

## Applications

The code for all applications can be found under the `inst` folder. However, if you are only looking for the Shiny GUI, you may find them:

  1. Simple Network Explorer, [here](https://callaghancorelab.shinyapps.io/simple_app/)
  
## Slides

You can find the slides here:

  1. TO DO
  
## Coding Resources 

R 101:
  
  1. [An introduction to R by the R Core team](https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf)
  2. [R for data science](https://www.google.com/search?q=r+for+data+science&oq=R+for+Da&aqs=chrome.0.35i39j46j69i57j0l2j69i60j69i61j69i60.1599j0j9&sourceid=chrome&ie=UTF-8)
  3. [Jenny Bryan's Stat 545](https://stat545.com/)
  
SQL + R:

  1. [R Studio's documentation](https://db.rstudio.com/getting-started/database-queries/)
  2. [The data carpentries](https://datacarpentry.org/R-ecology-lesson/05-r-and-databases.html)
  
SNA in R:

  1. [Katya Ognyanova's blog.](https://kateto.net/network-visualization)
  2. [Phil Murphy's materials on RPubs.](https://rpubs.com/pjmurphy)
  3. [Jesse Sadler's stuff.](https://www.jessesadler.com/post/network-analysis-with-r/)

Apps in R:

  1. [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/)
  2. [Mastering Shiny by Hadley Wickham.](https://mastering-shiny.org/)
  